export const sys_normal_disable={data:[
  {
      "dictCode": 6,
      "dictSort": 1,
      "dictLabel": "正常",
      "dictValue": "0",
      "dictType": "sys_normal_disable",
      "cssClass": "",
      "listClass": "primary",
      "isDefault": "Y",
      "remark": "正常状态",
      "createTime": "2023-12-26 12:50:18",
  },
  {
      "dictCode": 7,
      "dictSort": 2,
      "dictLabel": "停用",
      "dictValue": "1",
      "dictType": "sys_normal_disable",
      "cssClass": "",
      "listClass": "danger",
      "isDefault": "N",
      "remark": "停用状态",
      "createTime": "2023-12-26 12:50:18",
  },
  {
      "dictCode": "1760505124755070978",
      "dictSort": 3,
      "dictLabel": "yw",
      "dictValue": "yw",
      "dictType": "sys_normal_disable",
      "cssClass": "",
      "listClass": "default",
      "isDefault": "N",
      "remark": "",
      "createTime": "2024-02-22 11:21:45",
  },
]};

export const sys_user_sex = {data:[
  {
      "dictCode": 1,
      "dictSort": 1,
      "dictLabel": "男",
      "dictValue": "0",
      "dictType": "sys_user_sex",
      "cssClass": "",
      "listClass": "",
      "isDefault": "Y",
      "remark": "性别男",
      "createTime": "2023-12-26 12:50:18",
  },
  {
      "dictCode": 2,
      "dictSort": 2,
      "dictLabel": "女",
      "dictValue": "1",
      "dictType": "sys_user_sex",
      "cssClass": "",
      "listClass": "",
      "isDefault": "N",
      "remark": "性别女",
      "createTime": "2023-12-26 12:50:18",
  },
  {
      "dictCode": 3,
      "dictSort": 3,
      "dictLabel": "未知",
      "dictValue": "2",
      "dictType": "sys_user_sex",
      "cssClass": "",
      "listClass": "",
      "isDefault": "N",
      "remark": "性别未知",
      "createTime": "2023-12-26 12:50:18",
  },
  {
      "dictCode": "1774432186322640898",
      "dictSort": 4,
      "dictLabel": "问问",
      "dictValue": "ss",
      "dictType": "sys_user_sex",
      "cssClass": "",
      "listClass": "default",
      "isDefault": "N",
      "remark": "",
      "createTime": "2024-03-31 21:42:55",
  },
]};

export const sys_yes_no={
    data:[
        {
          "dictCode": 12,
          "dictSort": 1,
          "dictLabel": "是",
          "dictValue": "Y",
          "dictType": "sys_yes_no",
          "cssClass": "",
          "listClass": "primary",
          "isDefault": "Y",
          "remark": "系统默认是",
          "createTime": "2023-11-14 14:48:38",
        },
        {
          "dictCode": 13,
          "dictSort": 2,
          "dictLabel": "否",
          "dictValue": "N",
          "dictType": "sys_yes_no",
          "cssClass": "",
          "listClass": "danger",
          "isDefault": "N",
          "remark": "系统默认否",
          "createTime": "2023-11-14 14:48:38",
        },
      ],
};

export const sys_notice_status={data:[
  {
      "dictCode": 16,
      "dictSort": 1,
      "dictLabel": "正常",
      "dictValue": "0",
      "dictType": "sys_notice_status",
      "cssClass": "",
      "listClass": "primary",
      "isDefault": "Y",
      "remark": "正常状态",
      "createTime": "2023-11-18 17:26:39",
  },
  {
      "dictCode": 17,
      "dictSort": 2,
      "dictLabel": "关闭",
      "dictValue": "1",
      "dictType": "sys_notice_status",
      "cssClass": "",
      "listClass": "danger",
      "isDefault": "N",
      "remark": "关闭状态",
      "createTime": "2023-11-18 17:26:39",
  },
]};

export const sys_notice_type={data:[
  {
      "dictCode": "1760566528560324609",
      "dictSort": 0,
      "dictLabel": "1",
      "dictValue": "1",
      "dictType": "sys_notice_type",
      "cssClass": "",
      "listClass": "default",
      "isDefault": "N",
      "remark": "",
      "createTime": "2024-02-22 15:25:45",
  },
  {
      "dictCode": 14,
      "dictSort": 1,
      "dictLabel": "通知",
      "dictValue": "1",
      "dictType": "sys_notice_type",
      "cssClass": "",
      "listClass": "warning",
      "isDefault": "Y",
      "remark": "通知",
      "createTime": "2023-12-26 12:50:18",
  },
  {
      "dictCode": "1760567491517997057",
      "dictSort": 1,
      "dictLabel": "2",
      "dictValue": "2",
      "dictType": "sys_notice_type",
      "cssClass": "",
      "listClass": "default",
      "isDefault": "N",
      "remark": "",
      "createTime": "2024-02-22 15:29:34",
  },
  {
      "dictCode": 15,
      "dictSort": 2,
      "dictLabel": "公告",
      "dictValue": "2",
      "dictType": "sys_notice_type",
      "cssClass": "",
      "listClass": "success",
      "isDefault": "N",
      "remark": "公告",
      "createTime": "2023-12-26 12:50:18",
  },
]};