export const router =[
  {
      "name": "System",
      "path": "/system",
      "hidden": false,
      "redirect": "noRedirect",
      "component": "Layout",
      "alwaysShow": true,
      "meta": {
          "title": "系统管理",
          "icon": "system",
          "noCache": false,
          "link": null,
      },
      "children": [
          {
              "name": "123",
              "path": "123",
              "hidden": false,
              "component": "ParentView",
              "meta": {
                  "title": "22222",
                  "icon": "",
                  "noCache": false,
                  "link": null,
              },
          },
          {
              "name": "User",
              "path": "user",
              "hidden": false,
              "component": "system/user/index",
              "meta": {
                  "title": "用户管理",
                  "icon": "user",
                  "noCache": false,
                  "link": null,
              },
          },
          {
              "name": "Role",
              "path": "role",
              "hidden": false,
              "component": "system/role/index",
              "meta": {
                  "title": "角色管理",
                  "icon": "peoples",
                  "noCache": false,
                  "link": null,
              },
          },
          {
              "name": "Menu",
              "path": "menu",
              "hidden": false,
              "component": "system/menu/index",
              "meta": {
                  "title": "菜单管理",
                  "icon": "tree-table",
                  "noCache": false,
                  "link": null,
              },
          },
          {
              "name": "Dept",
              "path": "dept",
              "hidden": false,
              "component": "system/dept/index",
              "meta": {
                  "title": "部门管理",
                  "icon": "tree",
                  "noCache": false,
                  "link": null,
              },
          },
          {
              "name": "Post",
              "path": "post",
              "hidden": false,
              "component": "system/post/index",
              "meta": {
                  "title": "岗位管理",
                  "icon": "post",
                  "noCache": false,
                  "link": null,
              },
          },
          {
              "name": "Dict",
              "path": "dict",
              "hidden": false,
              "component": "system/dict/index",
              "meta": {
                  "title": "字典管理",
                  "icon": "dict",
                  "noCache": false,
                  "link": null,
              },
          },
          {
              "name": "Config",
              "path": "config",
              "hidden": false,
              "component": "system/config/index",
              "meta": {
                  "title": "参数设置",
                  "icon": "edit",
                  "noCache": false,
                  "link": null,
              },
          },
          {
              "name": "Notice",
              "path": "notice",
              "hidden": false,
              "component": "system/notice/index",
              "meta": {
                  "title": "通知公告",
                  "icon": "message",
                  "noCache": false,
                  "link": null,
              },
          },
          {
              "name": "Log",
              "path": "log",
              "hidden": false,
              "redirect": "noRedirect",
              "component": "ParentView",
              "alwaysShow": true,
              "meta": {
                  "title": "日志管理",
                  "icon": "log",
                  "noCache": false,
                  "link": null,
              },
              "children": [
                  {
                      "name": "Operlog",
                      "path": "operlog",
                      "hidden": false,
                      "component": "monitor/operlog/index",
                      "meta": {
                          "title": "操作日志",
                          "icon": "form",
                          "noCache": false,
                          "link": null,
                      },
                  },
                  {
                      "name": "Logininfor",
                      "path": "logininfor",
                      "hidden": false,
                      "component": "monitor/logininfor/index",
                      "meta": {
                          "title": "登录日志",
                          "icon": "logininfor",
                          "noCache": false,
                          "link": null,
                      },
                  },
              ],
          },
          {
              "name": "Oss",
              "path": "oss",
              "hidden": false,
              "component": "system/oss/index",
              "meta": {
                  "title": "文件管理",
                  "icon": "upload",
                  "noCache": false,
                  "link": null,
              },
          },
          {
              "name": "Client",
              "path": "client",
              "hidden": false,
              "component": "system/client/index",
              "meta": {
                  "title": "客户端管理",
                  "icon": "international",
                  "noCache": false,
                  "link": null,
              },
          },
          {
              "name": "685265",
              "path": "685265",
              "hidden": false,
              "component": "ParentView",
              "meta": {
                  "title": "65165",
                  "icon": "button",
                  "noCache": false,
                  "link": null,
              },
          },
      ],
  },
  {
      "name": "234",
      "path": "/234",
      "hidden": false,
      "redirect": "noRedirect",
      "component": "Layout",
      "alwaysShow": true,
      "meta": {
          "title": "234",
          "icon": "",
          "noCache": false,
          "link": null,
      },
      "children": [
          {
              "name": "13",
              "path": "13",
              "hidden": false,
              "component": "Layout",
              "meta": {
                  "title": "测试",
                  "icon": "",
                  "noCache": false,
                  "link": null,
              },
          },
          {
              "name": "12",
              "path": "12",
              "hidden": false,
              "component": "ParentView",
              "meta": {
                  "title": "1",
                  "icon": "",
                  "noCache": false,
                  "link": null,
              },
          },
      ],
  },
  {
      "name": "Test",
      "path": "/test",
      "hidden": false,
      "redirect": "noRedirect",
      "component": "Layout",
      "alwaysShow": true,
      "meta": {
          "title": "测试BUG",
          "icon": "bug",
          "noCache": false,
          "link": null,
      },
      "children": [
          {
              "name": "Test1",
              "path": "test1",
              "hidden": false,
              "component": "Layout",
              "meta": {
                  "title": "测试1",
                  "icon": "build",
                  "noCache": false,
                  "link": null,
              },
          },
      ],
  },
  {
      "path": "/",
      "hidden": false,
      "component": "Layout",
      "children": [
          {
              "name": "Operlog",
              "path": "operlog",
              "hidden": false,
              "component": "/123",
              "meta": {
                  "title": "一级菜单",
                  "icon": "build",
                  "noCache": false,
                  "link": null,
              },
          },
      ],
  },
  {
      "name": "111",
      "path": "/111",
      "hidden": false,
      "redirect": "noRedirect",
      "component": "Layout",
      "alwaysShow": true,
      "meta": {
          "title": "11111",
          "icon": "build",
          "noCache": false,
          "link": null,
      },
      "children": [
          {
              "name": "222",
              "path": "222",
              "hidden": false,
              "redirect": "noRedirect",
              "component": "ParentView",
              "alwaysShow": true,
              "meta": {
                  "title": "222.2",
                  "icon": "checkbox",
                  "noCache": false,
                  "link": null,
              },
              "children": [
                  {
                      "name": "333.3",
                      "path": "333.3",
                      "hidden": false,
                      "component": "Layout",
                      "meta": {
                          "title": "333",
                          "icon": "edit",
                          "noCache": false,
                          "link": null,
                      },
                  },
                  {
                      "name": "333",
                      "path": "333",
                      "hidden": false,
                      "component": "Layout",
                      "meta": {
                          "title": "333.1",
                          "icon": "documentation",
                          "noCache": false,
                          "link": null,
                      },
                  },
              ],
          },
          {
              "name": "22222",
              "path": "22222",
              "hidden": false,
              "redirect": "noRedirect",
              "component": "ParentView",
              "alwaysShow": true,
              "meta": {
                  "title": "222.1",
                  "icon": "build",
                  "noCache": false,
                  "link": null,
              },
              "children": [
                  {
                      "name": "333",
                      "path": "333",
                      "hidden": false,
                      "component": "Layout",
                      "meta": {
                          "title": "333.2",
                          "icon": "chart",
                          "noCache": false,
                          "link": null,
                      },
                  },
                  {
                      "name": "3333",
                      "path": "3333",
                      "hidden": false,
                      "component": "Layout",
                      "meta": {
                          "title": "333.1",
                          "icon": "code",
                          "noCache": false,
                          "link": null,
                      },
                  },
              ],
          },
      ],
  },
  {
      "name": "Test",
      "path": "/test",
      "hidden": false,
      "component": "Layout",
      "meta": {
          "title": "ceshi",
          "icon": "404",
          "noCache": false,
          "link": null,
      },
  },
  {
      "name": "Root",
      "path": "/root",
      "hidden": false,
      "component": "Layout",
      "meta": {
          "title": "商品信息管理",
          "icon": "404",
          "noCache": false,
          "link": null,
      },
  },
  {
      "name": "/portal",
      "path": "//portal",
      "hidden": false,
      "redirect": "noRedirect",
      "component": "Layout",
      "alwaysShow": true,
      "meta": {
          "title": "门户",
          "icon": "list",
          "noCache": false,
          "link": null,
      },
      "children": [
          {
              "name": "/portal/private",
              "path": "/portal/private",
              "hidden": false,
              "component": "/portal/private/index",
              "meta": {
                  "title": "个人门户",
                  "icon": "list",
                  "noCache": false,
                  "link": null,
              },
          },
          {
              "name": "Private",
              "path": "private",
              "hidden": false,
              "component": "portal/private/index",
              "meta": {
                  "title": "个人门户2",
                  "icon": "list",
                  "noCache": false,
                  "link": null,
              },
          },
      ],
  },
  {
      "path": "/",
      "hidden": false,
      "component": "Layout",
      "children": [
          {
              "name": "/componentDemo",
              "path": "/componentDemo",
              "hidden": false,
              "meta": {
                  "title": "组件DEMO",
                  "icon": "build",
                  "noCache": false,
                  "link": null,
              },
          },
      ],
  },
  {
      "path": "/",
      "hidden": false,
      "component": "Layout",
      "children": [
          {
              "name": "ComponentDemo",
              "path": "componentDemo",
              "hidden": false,
              "component": "componentDemo/index",
              "meta": {
                  "title": "组件DEMO1",
                  "icon": "build",
                  "noCache": false,
                  "link": null,
              },
          },
      ],
  },
  {
      "path": "/",
      "hidden": false,
      "component": "Layout",
      "children": [
          {
              "name": "ComponentsDemo",
              "path": "componentsDemo",
              "hidden": false,
              "component": "componentsDemo/index",
              "meta": {
                  "title": "组件DEMO2",
                  "icon": "bug",
                  "noCache": false,
                  "link": null,
              },
          },
      ],
  },
  {
      "name": "Order",
      "path": "/order",
      "hidden": false,
      "redirect": "noRedirect",
      "component": "Layout",
      "alwaysShow": true,
      "meta": {
          "title": "订单",
          "icon": "form",
          "noCache": false,
          "link": null,
      },
      "children": [
          {
              "name": "Pertty",
              "path": "pertty",
              "hidden": false,
              "component": "order/pertty/index",
              "meta": {
                  "title": "订单",
                  "icon": "form",
                  "noCache": false,
                  "link": null,
              },
          },
          {
              "name": "Order/pertty/logistics",
              "path": "order/pertty/logistics",
              "hidden": false,
              "component": "Layout",
              "meta": {
                  "title": "物流预警",
                  "icon": "checkbox",
                  "noCache": false,
                  "link": null,
              },
          },
          {
              "name": "Pertty",
              "path": "pertty",
              "hidden": false,
              "component": "order/pertty/logistics",
              "meta": {
                  "title": "物流预警-1",
                  "icon": "dict",
                  "noCache": false,
                  "link": null,
              },
          },
      ],
  },
  {
      "name": "Order",
      "path": "/order",
      "hidden": false,
      "redirect": "noRedirect",
      "component": "Layout",
      "alwaysShow": true,
      "meta": {
          "title": "订单1",
          "icon": "documentation",
          "noCache": false,
          "link": null,
      },
      "children": [
          {
              "name": "Pertty",
              "path": "pertty",
              "hidden": false,
              "component": "order/pertty/index",
              "meta": {
                  "title": "订单",
                  "icon": "",
                  "noCache": false,
                  "link": null,
              },
          },
      ],
  },
  {
      "path": "/",
      "hidden": false,
      "component": "Layout",
      "children": [
          {
              "name": "Order/pertty/logistics",
              "path": "order/pertty/logistics",
              "hidden": false,
              "component": "order/pertty/logistics",
              "meta": {
                  "title": "物流预警",
                  "icon": "color",
                  "noCache": false,
                  "link": null,
              },
          },
      ],
  },
  {
      "path": "/",
      "hidden": false,
      "component": "Layout",
      "children": [
          {
              "name": "22",
              "path": "22",
              "hidden": false,
              "meta": {
                  "title": "测试123",
                  "icon": "build",
                  "noCache": false,
                  "link": null,
              },
          },
      ],
  },
  {
      "name": "Tenant",
      "path": "/tenant",
      "hidden": false,
      "redirect": "noRedirect",
      "component": "Layout",
      "alwaysShow": true,
      "meta": {
          "title": "租户管理",
          "icon": "chart",
          "noCache": false,
          "link": null,
      },
      "children": [
          {
              "name": "Tenant",
              "path": "tenant",
              "hidden": false,
              "component": "system/tenant/index",
              "meta": {
                  "title": "租户管理",
                  "icon": "list",
                  "noCache": false,
                  "link": null,
              },
          },
          {
              "name": "TenantPackage",
              "path": "tenantPackage",
              "hidden": false,
              "component": "system/tenantPackage/index",
              "meta": {
                  "title": "租户套餐管理",
                  "icon": "form",
                  "noCache": false,
                  "link": null,
              },
          },
      ],
  },
  {
      "name": "Date",
      "path": "/date",
      "hidden": false,
      "redirect": "noRedirect",
      "component": "Layout",
      "alwaysShow": true,
      "meta": {
          "title": "影像管理",
          "icon": "cascader",
          "noCache": false,
          "link": null,
      },
      "children": [
          {
              "name": "Tasks",
              "path": "tasks",
              "hidden": false,
              "component": "date/tasks/index",
              "meta": {
                  "title": "任务列表",
                  "icon": "build",
                  "noCache": false,
                  "link": null,
              },
          },
      ],
  },
  {
      "name": "Monitor",
      "path": "/monitor",
      "hidden": false,
      "redirect": "noRedirect",
      "component": "Layout",
      "alwaysShow": true,
      "meta": {
          "title": "系统监控",
          "icon": "monitor",
          "noCache": false,
          "link": null,
      },
      "children": [
          {
              "name": "Online",
              "path": "online",
              "hidden": false,
              "component": "monitor/online/index",
              "meta": {
                  "title": "在线用户",
                  "icon": "online",
                  "noCache": false,
                  "link": null,
              },
          },
          {
              "name": "Admin",
              "path": "Admin",
              "hidden": false,
              "component": "monitor/admin/index",
              "meta": {
                  "title": "Admin监控",
                  "icon": "dashboard",
                  "noCache": false,
                  "link": null,
              },
          },
          {
              "name": "Powerjob",
              "path": "powerjob",
              "hidden": false,
              "component": "monitor/powerjob/index",
              "meta": {
                  "title": "任务调度中心",
                  "icon": "job",
                  "noCache": false,
                  "link": null,
              },
          },
          {
              "name": "Cache",
              "path": "cache",
              "hidden": false,
              "component": "monitor/cache/index",
              "meta": {
                  "title": "缓存监控",
                  "icon": "redis",
                  "noCache": false,
                  "link": null,
              },
          },
      ],
  },
  {
      "name": "Tool",
      "path": "/tool",
      "hidden": false,
      "redirect": "noRedirect",
      "component": "Layout",
      "alwaysShow": true,
      "meta": {
          "title": "系统工具",
          "icon": "tool",
          "noCache": false,
          "link": null,
      },
      "children": [
          {
              "name": "Build",
              "path": "build",
              "hidden": false,
              "component": "tool/build/index",
              "meta": {
                  "title": "表单构建",
                  "icon": "build",
                  "noCache": false,
                  "link": null,
              },
          },
          {
              "name": "Gen",
              "path": "gen",
              "hidden": false,
              "component": "tool/gen/index",
              "meta": {
                  "title": "代码生成",
                  "icon": "code",
                  "noCache": false,
                  "link": null,
              },
          },
      ],
  },
  {
      "name": "Https://gitee.com/dromara/RuoYi-Vue-Plus",
      "path": "https://gitee.com/dromara/RuoYi-Vue-Plus",
      "hidden": false,
      "redirect": "noRedirect",
      "component": "Layout",
      "alwaysShow": true,
      "meta": {
          "title": "PLUS官网",
          "icon": "guide",
          "noCache": false,
          "link": "https://gitee.com/dromara/RuoYi-Vue-Plus",
      },
      "children": [
          {
              "name": "Aaa",
              "path": "aaa",
              "hidden": false,
              "component": "aaa",
              "query": "aaa",
              "meta": {
                  "title": "aaa",
                  "icon": "bug",
                  "noCache": false,
                  "link": null,
              },
          },
      ],
  },
  {
      "name": "Demo",
      "path": "/demo",
      "hidden": false,
      "redirect": "noRedirect",
      "component": "Layout",
      "alwaysShow": true,
      "meta": {
          "title": "测试菜单",
          "icon": "star",
          "noCache": false,
          "link": null,
      },
      "children": [
          {
              "name": "Test2",
              "path": "test2",
              "hidden": false,
              "component": "test2",
              "meta": {
                  "title": "222",
                  "icon": "tree-table",
                  "noCache": true,
                  "link": null,
              },
          },
          {
              "name": "Demo",
              "path": "demo",
              "hidden": false,
              "component": "demo/demo/index",
              "meta": {
                  "title": "测试单表",
                  "icon": "#",
                  "noCache": false,
                  "link": null,
              },
          },
          {
              "name": "Tree",
              "path": "tree",
              "hidden": false,
              "component": "demo/tree/index",
              "meta": {
                  "title": "测试树表",
                  "icon": "#",
                  "noCache": false,
                  "link": null,
              },
          },
          {
              "name": "Test",
              "path": "test",
              "hidden": false,
              "component": "Layout",
              "meta": {
                  "title": "111",
                  "icon": "qq",
                  "noCache": false,
                  "link": null,
              },
          },
          {
              "name": "Test3",
              "path": "test3",
              "hidden": false,
              "component": "test3",
              "meta": {
                  "title": "333",
                  "icon": "theme",
                  "noCache": true,
                  "link": null,
              },
          },
      ],
  },
  {
      "name": "Https://www.baidu.com",
      "path": "https://www.baidu.com",
      "hidden": false,
      "component": "Layout",
      "meta": {
          "title": "大屏统计",
          "icon": "chart",
          "noCache": false,
          "link": "https://www.baidu.com",
      },
  },
];