export const userInfo={
  "user": {
      "userId": 1,
      "tenantId": "000000",
      "deptId": 103,
      "userName": "admin",
      "nickName": "疯狂的狮子Li",
      "userType": "sys_user",
      "email": "crazyLionLi@163.com",
      "phonenumber": "15888888888",
      "sex": "1",
      "avatar": "http://43.138.9.96:9000/ruoyi/2024/04/01/f32f43d64172420aa7ea1f8e0572fb06.png",
      "status": "0",
      "loginIp": "125.76.40.204",
      "loginDate": "2024-04-07 11:29:20",
      "remark": "管理员",
      "createTime": "2023-12-26 12:50:17",
      "dept": {
          "deptId": 103,
          "parentId": 101,
          "parentName": null,
          "ancestors": "0,100,101",
          "deptName": "研发部门",
          "orderNum": 1,
          "leader": 1,
          "leaderName": null,
          "phone": null,
          "email": "xxx@qq.com",
          "status": "0",
          "createTime": null,
      },
      "roles": [
          {
              "roleId": 1,
              "roleName": "超级管理员",
              "roleKey": "superadmin",
              "roleSort": 1,
              "dataScope": "1",
              "menuCheckStrictly": null,
              "deptCheckStrictly": null,
              "status": "0",
              "remark": "管理员",
              "createTime": null,
              "flag": false,
              "superAdmin": true,
          },
      ],
      "roleIds": null,
      "postIds": null,
      "roleId": 1,
  },
  "permissions": [
      "*:*:*",
  ],
  "roles": [
      "superadmin",
  ],
};