export const userListData={rows:[
  {
      "userId": 1,
      "tenantId": null,
      "deptId": 103,
      "userName": "admin",
      "nickName": "疯狂的狮子Li",
      "userType": null,
      "email": "crazyLionLi@163.com",
      "phonenumber": "15888888888",
      "sex": "1",
      "avatar": "http://43.138.9.96:9000/ruoyi/2024/04/01/f32f43d64172420aa7ea1f8e0572fb06.png",
      "status": "0",
      "loginIp": "223.71.38.212",
      "loginDate": "2024-04-07 11:20:17",
      "remark": "管理员",
      "createTime": "2023-12-26 12:50:17",
      "dept": {
          "deptId": 103,
          "parentId": null,
          "parentName": null,
          "ancestors": null,
          "deptName": "研发部门",
          "orderNum": null,
          "leader": 1,
          "leaderName": "admin",
          "phone": null,
          "email": null,
          "status": null,
          "createTime": null,
      },
      "roles": [
          {
              "roleId": null,
              "roleName": null,
              "roleKey": null,
              "roleSort": null,
              "dataScope": null,
              "menuCheckStrictly": null,
              "deptCheckStrictly": null,
              "status": null,
              "remark": "管理员",
              "createTime": null,
              "flag": false,
              "superAdmin": false,
          },
      ],
      "roleIds": null,
      "postIds": null,
      "roleId": null,
  },
  {
      "userId": 2,
      "tenantId": null,
      "deptId": 105,
      "userName": "lionli",
      "nickName": "疯狂的狮子Li",
      "userType": null,
      "email": "crazyLionLi@qq.com",
      "phonenumber": "15666666666",
      "sex": "1",
      "avatar": null,
      "status": "0",
      "loginIp": "112.31.12.211",
      "loginDate": "2024-04-01 13:51:40",
      "remark": "测试员",
      "createTime": "2023-12-26 12:50:17",
      "dept": {
          "deptId": 105,
          "parentId": null,
          "parentName": null,
          "ancestors": null,
          "deptName": "测试部门",
          "orderNum": null,
          "leader": null,
          "leaderName": null,
          "phone": null,
          "email": null,
          "status": null,
          "createTime": null,
      },
      "roles": [
          {
              "roleId": null,
              "roleName": null,
              "roleKey": null,
              "roleSort": null,
              "dataScope": null,
              "menuCheckStrictly": null,
              "deptCheckStrictly": null,
              "status": null,
              "remark": "测试员",
              "createTime": null,
              "flag": false,
              "superAdmin": false,
          },
      ],
      "roleIds": null,
      "postIds": null,
      "roleId": null,
  },
  {
      "userId": 3,
      "tenantId": null,
      "deptId": 108,
      "userName": "test",
      "nickName": "本部门及以下 密码666666",
      "userType": null,
      "email": "",
      "phonenumber": "",
      "sex": "0",
      "avatar": null,
      "status": "0",
      "loginIp": "113.27.20.37",
      "loginDate": "2024-04-03 16:32:55",
      "remark": null,
      "createTime": "2023-12-26 12:50:23",
      "dept": {
          "deptId": 108,
          "parentId": null,
          "parentName": null,
          "ancestors": null,
          "deptName": "市场部门",
          "orderNum": null,
          "leader": null,
          "leaderName": null,
          "phone": null,
          "email": null,
          "status": null,
          "createTime": null,
      },
      "roles": [],
      "roleIds": null,
      "postIds": null,
      "roleId": null,
  },
  {
      "userId": 4,
      "tenantId": null,
      "deptId": 102,
      "userName": "test1",
      "nickName": "仅本人 密码666666",
      "userType": null,
      "email": "",
      "phonenumber": "",
      "sex": "0",
      "avatar": null,
      "status": "0",
      "loginIp": "127.0.0.1",
      "loginDate": "2023-12-26 12:50:23",
      "remark": null,
      "createTime": "2023-12-26 12:50:23",
      "dept": {
          "deptId": 102,
          "parentId": null,
          "parentName": null,
          "ancestors": null,
          "deptName": "长沙分公司",
          "orderNum": null,
          "leader": null,
          "leaderName": null,
          "phone": null,
          "email": null,
          "status": null,
          "createTime": null,
      },
      "roles": [],
      "roleIds": null,
      "postIds": null,
      "roleId": null,
  },
  {
      "userId": 10000,
      "tenantId": null,
      "deptId": 2,
      "userName": "2",
      "nickName": "2",
      "userType": null,
      "email": "1401431383@QQ.COM",
      "phonenumber": "13213161652",
      "sex": "0",
      "avatar": null,
      "status": "0",
      "loginIp": "",
      "loginDate": null,
      "remark": null,
      "createTime": "2024-04-02 09:56:41",
      "dept": {
          "deptId": 2,
          "parentId": null,
          "parentName": null,
          "ancestors": null,
          "deptName": null,
          "orderNum": null,
          "leader": null,
          "leaderName": null,
          "phone": null,
          "email": null,
          "status": null,
          "createTime": null,
      },
      "roles": [],
      "roleIds": null,
      "postIds": null,
      "roleId": null,
  },
  {
      "userId": "1773527549432291330",
      "tenantId": null,
      "deptId": 103,
      "userName": "fafafa",
      "nickName": "qqqq",
      "userType": null,
      "email": "",
      "phonenumber": "15567892341",
      "sex": "1",
      "avatar": null,
      "status": "0",
      "loginIp": "182.45.247.222",
      "loginDate": "2024-04-02 15:55:37",
      "remark": "beizhu",
      "createTime": "2024-03-29 09:48:13",
      "dept": {
          "deptId": 103,
          "parentId": null,
          "parentName": null,
          "ancestors": null,
          "deptName": "研发部门",
          "orderNum": null,
          "leader": 1,
          "leaderName": "admin",
          "phone": null,
          "email": null,
          "status": null,
          "createTime": null,
      },
      "roles": [
          {
              "roleId": null,
              "roleName": null,
              "roleKey": null,
              "roleSort": null,
              "dataScope": null,
              "menuCheckStrictly": null,
              "deptCheckStrictly": null,
              "status": null,
              "remark": "beizhu",
              "createTime": null,
              "flag": false,
              "superAdmin": false,
          },
      ],
      "roleIds": null,
      "postIds": null,
      "roleId": null,
  },
  {
      "userId": "1773603782123839489",
      "tenantId": null,
      "deptId": null,
      "userName": "sk001",
      "nickName": "sk001",
      "userType": null,
      "email": "",
      "phonenumber": "",
      "sex": "0",
      "avatar": null,
      "status": "0",
      "loginIp": "",
      "loginDate": null,
      "remark": "",
      "createTime": "2024-03-29 14:51:08",
      "dept": null,
      "roles": [
          {
              "roleId": null,
              "roleName": null,
              "roleKey": null,
              "roleSort": null,
              "dataScope": null,
              "menuCheckStrictly": null,
              "deptCheckStrictly": null,
              "status": null,
              "remark": "",
              "createTime": null,
              "flag": false,
              "superAdmin": false,
          },
      ],
      "roleIds": null,
      "postIds": null,
      "roleId": null,
  },
  {
      "userId": "1774995520507863042",
      "tenantId": null,
      "deptId": null,
      "userName": "233",
      "nickName": "1221",
      "userType": null,
      "email": "",
      "phonenumber": "",
      "sex": "0",
      "avatar": null,
      "status": "0",
      "loginIp": "",
      "loginDate": null,
      "remark": "",
      "createTime": "2024-04-02 11:01:25",
      "dept": null,
      "roles": [
          {
              "roleId": null,
              "roleName": null,
              "roleKey": null,
              "roleSort": null,
              "dataScope": null,
              "menuCheckStrictly": null,
              "deptCheckStrictly": null,
              "status": null,
              "remark": "",
              "createTime": null,
              "flag": false,
              "superAdmin": false,
          },
      ],
      "roleIds": null,
      "postIds": null,
      "roleId": null,
  },
  {
      "userId": "1775058566668345346",
      "tenantId": null,
      "deptId": 100,
      "userName": "1231",
      "nickName": "123",
      "userType": null,
      "email": "",
      "phonenumber": "",
      "sex": "0",
      "avatar": null,
      "status": "0",
      "loginIp": "",
      "loginDate": null,
      "remark": "",
      "createTime": "2024-04-02 15:11:56",
      "dept": {
          "deptId": 100,
          "parentId": null,
          "parentName": null,
          "ancestors": null,
          "deptName": "XXX科技",
          "orderNum": null,
          "leader": null,
          "leaderName": null,
          "phone": null,
          "email": null,
          "status": null,
          "createTime": null,
      },
      "roles": [
          {
              "roleId": null,
              "roleName": null,
              "roleKey": null,
              "roleSort": null,
              "dataScope": null,
              "menuCheckStrictly": null,
              "deptCheckStrictly": null,
              "status": null,
              "remark": "",
              "createTime": null,
              "flag": false,
              "superAdmin": false,
          },
      ],
      "roleIds": null,
      "postIds": null,
      "roleId": null,
  },
  {
      "userId": "1775104189794869250",
      "tenantId": null,
      "deptId": 109,
      "userName": "12",
      "nickName": "xy",
      "userType": null,
      "email": "",
      "phonenumber": "",
      "sex": "0",
      "avatar": null,
      "status": "0",
      "loginIp": "",
      "loginDate": null,
      "remark": "",
      "createTime": "2024-04-02 18:13:13",
      "dept": {
          "deptId": 109,
          "parentId": null,
          "parentName": null,
          "ancestors": null,
          "deptName": "财务部门",
          "orderNum": null,
          "leader": null,
          "leaderName": null,
          "phone": null,
          "email": null,
          "status": null,
          "createTime": null,
      },
      "roles": [
          {
              "roleId": null,
              "roleName": null,
              "roleKey": null,
              "roleSort": null,
              "dataScope": null,
              "menuCheckStrictly": null,
              "deptCheckStrictly": null,
              "status": null,
              "remark": "",
              "createTime": null,
              "flag": false,
              "superAdmin": false,
          },
      ],
      "roleIds": null,
      "postIds": null,
      "roleId": null,
  },
],total:14};