export const configData={
  rows:[
    {
        "configId": 1,
        "configName": "主框架页-默认皮肤样式名称",
        "configKey": "sys.index.skinName",
        "configValue": "skin-blue",
        "configType": "Y",
        "remark": "蓝色 skin-blue、绿色 skin-green、紫色 skin-purple、红色 skin-red、黄色 skin-yellow",
        "createTime": "2023-12-26 12:50:18",
    },
    {
        "configId": 2,
        "configName": "用户管理-账号初始密码",
        "configKey": "sys.user.initPassword",
        "configValue": "123456",
        "configType": "Y",
        "remark": "初始化密码 123456",
        "createTime": "2023-12-26 12:50:18",
    },
    {
        "configId": 3,
        "configName": "主框架页-侧边栏主题",
        "configKey": "sys.index.sideTheme",
        "configValue": "theme-dark",
        "configType": "Y",
        "remark": "深色主题theme-dark，浅色主题theme-light",
        "createTime": "2023-12-26 12:50:18",
    },
    {
        "configId": 5,
        "configName": "账号自助-是否开启用户注册功能",
        "configKey": "sys.account.registerUser",
        "configValue": "false",
        "configType": "Y",
        "remark": "是否开启注册用户功能（true开启，false关闭）",
        "createTime": "2023-12-26 12:50:18",
    },
    {
        "configId": 11,
        "configName": "OSS预览列表资源开关",
        "configKey": "sys.oss.previewListResource",
        "configValue": "true",
        "configType": "Y",
        "remark": "true:开启, false:关闭",
        "createTime": "2023-12-26 12:50:18",
    },
    {
        "configId": "1773545347265060865",
        "configName": "test",
        "configKey": "ls",
        "configValue": "特推三推四推三推四",
        "configType": "Y",
        "remark": "测试\n",
        "createTime": "2024-03-29 10:58:56",
    },
],
total:6};