export const role = {
  rows: [
    {
      roleId: 1,
      roleName: '超级管理员',
      roleKey: 'superadmin',
      roleSort: 1,
      dataScope: '1',
      menuCheckStrictly: true,
      deptCheckStrictly: true,
      status: '0',
      remark: '超级管理员',
      createTime: '2023-12-26 12:50:17',
      flag: false,
      superAdmin: true,
    },
    {
      roleId: '1773910640353075201',
      roleName: '湖人挺好',
      roleKey: '5346',
      roleSort: 1,
      dataScope: '1',
      menuCheckStrictly: true,
      deptCheckStrictly: true,
      status: '0',
      remark: '',
      createTime: '2024-03-30 11:10:29',
      flag: false,
      superAdmin: false,
    },
    {
      roleId: '1774068365716348930',
      roleName: '采购员',
      roleKey: '111',
      roleSort: 1,
      dataScope: '1',
      menuCheckStrictly: true,
      deptCheckStrictly: true,
      status: '0',
      remark: '',
      createTime: '2024-03-30 21:37:14',
      flag: false,
      superAdmin: false,
    },
    {
      roleId: '1774256778532872193',
      roleName: '1',
      roleKey: '1',
      roleSort: 1,
      dataScope: '1',
      menuCheckStrictly: true,
      deptCheckStrictly: true,
      status: '0',
      remark: '',
      createTime: '2024-03-31 10:05:55',
      flag: false,
      superAdmin: false,
    },
    {
      roleId: '1774275078134423553',
      roleName: '语文',
      roleKey: 'q',
      roleSort: 1,
      dataScope: '1',
      menuCheckStrictly: true,
      deptCheckStrictly: true,
      status: '0',
      remark: '',
      createTime: '2024-03-31 11:18:38',
      flag: false,
      superAdmin: false,
    },
    {
      roleId: '1774275134459731970',
      roleName: '数学',
      roleKey: 'w',
      roleSort: 1,
      dataScope: '1',
      menuCheckStrictly: true,
      deptCheckStrictly: true,
      status: '0',
      remark: '',
      createTime: '2024-03-31 11:18:51',
      flag: false,
      superAdmin: false,
    },
    {
      roleId: '1774275178344734721',
      roleName: '英语',
      roleKey: 'e',
      roleSort: 1,
      dataScope: '1',
      menuCheckStrictly: true,
      deptCheckStrictly: true,
      status: '0',
      remark: '',
      createTime: '2024-03-31 11:19:02',
      flag: false,
      superAdmin: false,
    },
    {
      roleId: '1774275232400924674',
      roleName: '物理',
      roleKey: 'r',
      roleSort: 1,
      dataScope: '1',
      menuCheckStrictly: true,
      deptCheckStrictly: true,
      status: '0',
      remark: '',
      createTime: '2024-03-31 11:19:15',
      flag: false,
      superAdmin: false,
    },
    {
      roleId: '1774275309605478401',
      roleName: '地理',
      roleKey: 't',
      roleSort: 1,
      dataScope: '1',
      menuCheckStrictly: true,
      deptCheckStrictly: true,
      status: '0',
      remark: '',
      createTime: '2024-03-31 11:19:33',
      flag: false,
      superAdmin: false,
    },
    {
      roleId: '1774827942049210370',
      roleName: '一天',
      roleKey: '456',
      roleSort: 1,
      dataScope: '1',
      menuCheckStrictly: true,
      deptCheckStrictly: true,
      status: '0',
      remark: '',
      createTime: '2024-04-01 23:55:31',
      flag: false,
      superAdmin: false,
    },
  ],
  total: 25,
};

export const sysStatu={data:[
  {
      "dictCode": 6,
      "dictSort": 1,
      "dictLabel": "正常",
      "dictValue": "0",
      "dictType": "sys_normal_disable",
      "cssClass": "",
      "listClass": "primary",
      "isDefault": "Y",
      "remark": "正常状态",
      "createTime": "2023-12-26 12:50:18",
  },
  {
      "dictCode": 7,
      "dictSort": 2,
      "dictLabel": "停用",
      "dictValue": "1",
      "dictType": "sys_normal_disable",
      "cssClass": "",
      "listClass": "danger",
      "isDefault": "N",
      "remark": "停用状态",
      "createTime": "2023-12-26 12:50:18",
  },
  {
      "dictCode": "1760505124755070978",
      "dictSort": 3,
      "dictLabel": "yw",
      "dictValue": "yw",
      "dictType": "sys_normal_disable",
      "cssClass": "",
      "listClass": "default",
      "isDefault": "N",
      "remark": "",
      "createTime": "2024-02-22 11:21:45",
  },
]};